kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aramadan-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "update", "create", "delete", "patch"]
